#!/bin/bash

if [[ ! -n $2 ]]; then
  echo "$0 <tiddlywiki.html> <public HTML directory> [archive]"
  echo "** the 'archive' command at the end allows users to load snapshots"
  exit 0
fi

DIFFSIZE=0
SNAP="$2/wiki.html"

if [ -f "$SNAP.snap" ]; then
  diff -wn "$SNAP.snap" "$1" > "$SNAP.diff"
  DIFFSIZE=$(stat -c%s "$SNAP.diff")

  if [ $DIFFSIZE -gt 2097152 ]; then
    cp "$1" "$SNAP.snap"
    rm -f "$SNAP.diff"
    DIFFSIZE=0
  fi
else
  cp "$1" "$SNAP.snap"
fi

SNAPSIZE=$(stat -c%s "$SNAP.snap")
OUTDIR=$(dirname "$0")

cp "$1" "$SNAP"
cp "$OUTDIR/index.html" "$2/"

if [ "$3" = "archive" ]; then
  number=0
  arch="$2/archives"
  mkdir -p "$arch"
  suffix="$(printf -- '%08d' "$number")"
  while test -e "$arch/$suffix.json"; do
    (( ++number ))
    if test -f "$arch/$suffix.snap"; then
      lastsnap="archives/$suffix.snap"
    fi
    suffix="$(printf -- '%08d' "$number")"
  done

  snapdate=$(date -uIseconds)
  if [ $DIFFSIZE -gt 0 ]; then
    mv "$SNAP.diff" "$arch/$suffix.diff"
    diffentry=", \"diffpath\": \"archives/$suffix.diff\""
  else
    mv "$SNAP.snap" "$arch/$suffix.snap"
    lastsnap="archives/$suffix.snap"
  fi

  echo "{\"size\": $SNAPSIZE, \"diffsize\": $DIFFSIZE, \"path\": \"$lastsnap\"$diffentry}" > "$arch/$suffix.json"
  cp "$arch/$suffix.json" "$SNAP.json"
  echo "archives/$suffix.json" >> "$SNAP.lst"
else
  echo "{\"size\": $SNAPSIZE, \"diffsize\": $DIFFSIZE, \"path\": \"wiki.html.snap\", \"diffpath\": \"wiki.html.diff\"}" > "$SNAP.json"
fi
